### ISSUE TITLE
Error when gaining artifact power

### ISSUE THREAD

**Issue by Gethe** [Rainrider/LibArtifactData-1.0#2] opened 2016-08-31 19:55 UTC
``` lua
1x ...lUI\Libs\LibArtifactData-1.0\LibArtifactData-1.0-5.lua:354: attempt to index local 'artifact' (a nil value)
...lUI\Libs\LibArtifactData-1.0\LibArtifactData-1.0-5.lua:354: in function '?'
...lUI\Libs\LibArtifactData-1.0\LibArtifactData-1.0-5.lua:67: in function <...lUI\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:67>
```

This may be related to issue #1

**Comment by Rainrider** [comment] 2016-08-31 21:39
Hm, it seems LAD fails to get artifact data for some reason. I won't have access to WoW before Sunday, won't be able to do much about it until then.

**Comment by Rainrider** [comment] 2016-09-03 20:46
This can't be related to #1 as it would have error-ed on line 351 (when calling GetNumPurchasableTraits). I'll get RealUI and try to reproduce the error.

**Comment by Rainrider** [comment] 2016-09-04 12:17
Can't reproduce with RealUI. Did a clean install from wowinterface. Are you using Exorsus Raid Tools or something else that breaks the artifact ui?

**Comment by VaporAPX** [comment] 2016-09-04 20:29
I also get a similar error every time I use an item to gain artifact power.

34x ...bar\Libs\LibArtifactData-1.0\LibArtifactData-1.0-6.lua:351: attempt to index local 'artifact' (a nil value)
...bar\Libs\LibArtifactData-1.0\LibArtifactData-1.0-6.lua:351: in function `?'
...bar\Libs\LibArtifactData-1.0\LibArtifactData-1.0-6.lua:67: in function <...bar\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:67>

Locals:
event = "ARTIFACT_XP_UPDATE"
GetInfo = <function> defined =[C]:-1
itemID = 128289
_ = 128288
_ = "Scale of the Earth-Warder"
_ = 1139451
unspentPower = 2275
numRanksPurchased = 15
numRanksPurchasable = 0
power = 2275
maxPower = 11280
artifact = nil
(_temporary) = 11280
(_temporary) = 0
(_temporary) = 2275
(_temporary) = 11280
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = "attempt to index local 'artifact' (a nil value)"
IsAtForge = <function> defined =[C]:-1
GetArtifactInfo = <function> defined =[C]:-1
GetEquippedArtifactInfo = <function> defined =[C]:-1
GetNumPurchasableTraits = <function> defined @FrameXML\MainMenuBar.lua:124
artifacts = <table> {
 knowledgeMultiplier = 1
 knowledgeLevel = 0
}
ScanTraits = <function> defined @XIV_Databar\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:162
InformTraitsChanged = <function> defined @XIV_Databar\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:128
Debug = <function> defined @XIV_Databar\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:9
lib = <table> {
 GetActiveArtifactID = <function> defined @XIV_Databar\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:408
 GetArtifactKnowledge = <function> defined @XIV_Databar\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:459
 ForceUpdate = <function> defined @XIV_Databar\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:492
 callbacks = <table> {
 }
 GetAcquiredArtifactPower = <function> defined @XIV_Databar\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:463
 GetArtifactRelics = <function> defined @XIV_Databar\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:441
 RegisterCallback = <function> defined @Dominos\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:116
 GetArtifactPower = <function> defined @XIV_Databar\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:450
 GetArtifactTraits = <function> defined @XIV_Databar\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:432
 UnregisterCallback = <function> defined @Dominos\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:179
 GetArtifactInfo = <function> defined @XIV_Databar\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:412
 GetNumObtainedArtifacts = <function> defined @XIV_Databar\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:421
 frame = <unnamed> {
 }
 GetAllArtifactsInfo = <function> defined @XIV_Databar\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:417
 UnregisterAllCallbacks = <function> defined @Dominos\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:200
}

**Comment by Rainrider** [comment] 2016-09-04 22:10
Could you please run the following two commands right after you encounter the error and tell me results?
1. `/dump LibStub("LibArtifactData-1.0"):GetArtifactInfo(128288)`
2. `/dump LibStub("LibArtifactData-1.0"):GetArtifactInfo(128289)`

**Comment by VaporAPX** [comment] 2016-09-04 22:19
Dump: value=LibStub("LibArtifactData-1.0"):GetArtifactInfo(128288)
[1]=128288,
[2]={
}

Dump: value=LibStub("LibArtifactData-1.0"):GetArtifactInfo(128289)
[1]=128289,
[2]={
}

Ran right after I clicked a usable AP upgrade.

**Comment by Rainrider** [comment] 2016-09-04 23:08
It seems that LAD failed to fetch the artifact data. Are you able to shift+right-click on the artifact to open the artifact ui? Do you hear some sounds from time to time as if you were socketing an item? Any other artifact related addons? I.e. Exorsus Raid Tools is known to cause problems.

**Comment by VaporAPX** [comment] 2016-09-04 23:23
When I had exorsus enabled after a reload ui it was constantly playing the sound over and over again of when you open and close a window, and any window I opened during that time would close, so something was being opened and closed over and over again.  Having exorsus disabled, I only get this error after using an AP upgrade token, and VERY rarely when I reload my ui after the error my artifact tree window will pop up with a blank tree saying "You haven't learned the talents for this artifact yet" or whatever the dialog is.

The second one is rare, but the original error I posted happens reliably every single time I use an AP token.  No other artifact addons, I use ouf_drk which also references and shows a status bar for artifact experience but that's it.  No issues right clicking and controlling my artifact.

**Comment by Rainrider** [comment] 2016-09-05 00:03
I pushed an alpha version to wowace. While I don't think it fixes the problems it should suppress the errors and hopefully LAD will pick up the data. It was enough to stop the ExRT madness at least.

Would you mind installing from [here](https://www.wowace.com/addons/libartifactdata-1-0/) as a stand-alone addon and telling me if the problem still persist?

**Comment by VaporAPX** [comment] 2016-09-05 00:12
Yep, it works with the standalone you just pushed, the error is gone.

**Comment by VaporAPX** [comment] 2016-09-05 00:33
Ok so I messed up and actually installed the release version 1.0 and didn't realize it until curse flashed as an update for the alpha you pushed.  When I had the 1.0 release running I had no errors, I updated to the alpha and as soon as I targeted a mob it flashed the following error, opened my right click artifact tree as a blank tree with "You have not yet learned the full potential of this artifact" in the middle. 

1x ...eLibArtifactData-1.0\LibArtifactData-1.0-7.lua:195: 'for' limit must be a number
...eLibArtifactData-1.0\LibArtifactData-1.0-7.lua:195: in function <...eLibArtifactData-1.0\LibArtifactData-1.0.lua:193>
...eLibArtifactData-1.0\LibArtifactData-1.0-7.lua:329: in function `?'
...eLibArtifactData-1.0\LibArtifactData-1.0-7.lua:67: in function <...eLibArtifactData-1.0\LibArtifactData-1.0.lua:67>

Locals:

**Comment by VaporAPX** [comment] 2016-09-05 00:34
A second error that popped with the one I just posted above using the alpha LAD.

64x ...eBlizzard_ArtifactUI\Blizzard_ArtifactUI.lua:41: attempt to compare number with nil
...eBlizzard_ArtifactUI\Blizzard_ArtifactUI.lua:41: in function `ArtifactUI_CanViewArtifact'
...ddOns\Blizzard_ArtifactUI\Blizzard_ArtifactPerks.lua:680: in function`EvaluateRelics'
...ddOns\Blizzard_ArtifactUI\Blizzard_ArtifactPerks.lua:541: in function <...ddOns\Blizzard_ArtifactUI\Blizzard_ArtifactPerks.lua:539>
[C]: in function `SetShown'
...eBlizzard_ArtifactUI\Blizzard_ArtifactUI.lua:172: in function`SetTab'
...eBlizzard_ArtifactUI\Blizzard_ArtifactUI.lua:138: in function `EvaulateForgeState'
...eBlizzard_ArtifactUI\Blizzard_ArtifactUI.lua:70: in function <...eBlizzard_ArtifactUI\Blizzard_ArtifactUI.lua:67>
[C]: in function`Show'
FrameXML\UIParent.lua:2336: in function `SetUIPanel'
FrameXML\UIParent.lua:2154: in function`ShowUIPanel'
FrameXML\UIParent.lua:2048: in function <FrameXML\UIParent.lua:2044>
[C]: in function `SetAttribute'
FrameXML\UIParent.lua:2830: in function <FrameXML\UIParent.lua:2818>
[C]: in function`ShowUIPanel'
FrameXML\UIParent.lua:1466: in function <FrameXML\UIParent.lua:891>

Locals:
(_temporary) = nil
(_temporary) = false
(*temporary) = "attempt to compare number with nil"

**Comment by Rainrider** [comment] 2016-09-05 00:37
So you don't have any other addons related to artifacts apart from XIV_Databar and oUF_Drk (the latter uses oUF_ArtifactPower, which is from me and I'm confident it does not cause the errors)? Exorsus still disabled?

**Comment by VaporAPX** [comment] 2016-09-05 00:42
Exorsus is still disabled yes, I use AdibuttonAuras as well.  The other name I've seen pop up in these errors is dominos, so I dunno if that has anything to do with whats causing the issues.

**Comment by Rainrider** [comment] 2016-09-05 01:03
Dominos is just the first loaded addon that contains CallbackHandler, which is a library that allows addons to send messages to each other. This is the reason it is listed in the reports.

Frankly, I don't know what causes the errors. You could try disabling all addons you have and try to reproduce the error. If this fails, enable them one at a time and try to reproduce again until it pops again. From your last report it seems it is a blizzard error.

**Comment by VaporAPX** [comment] 2016-09-05 01:55
I'll run through my addons and see if I can pinpoint when the error starts, using the new alpha LAD you uploaded.  I'll post back here a little later and update you with my findings.

**Comment by VaporAPX** [comment] 2016-09-05 04:57
So I've been playing for several hours now, and for some reason I haven't encountered the 2 errors again that I posted above, since moving to the stand alone alpha LAD.  I have no idea why, I didn't change anything, so I guess I'll keep my fingers crossed and say it's fixed? lol  Thanks for all the effort and replies today, appreciate it.

**Comment by Talyrius** [comment] 2016-09-05 05:07
@VaporAPX 
Those are the errors I referenced in #4.

**Comment by VaporAPX** [comment] 2016-09-05 21:24
Played all night last night, most of the morning with no issue.  Logged back in 5 mins ago, forgot to enable a mod so I did it from the interface panel, reloaded my UI and the 2 errors above popped, with the blank artifact UI.  So the issue is still there, I just have no idea what triggers it.

**Comment by Rainrider** [comment] 2016-09-06 06:47
So the question is: what mod did you enable. And what error messages did
you get

**Comment by nomad980** [comment] 2016-09-06 06:57
Guys are any of you using Tradeskill Master?

Ok, so I went through all my addons, and was able to pinpoint the one that isn't playing nice. The second I disabled TSM the issue went away.

**Comment by VaporAPX** [comment] 2016-09-06 16:33
Totally brain farted on my last reply, I meant to add that like @nomad980 has said above that it was indeed TSM that I enabled that started the issue.  It was the auctionDB module to be specific, I had the rest enabled but forgot about the auction module.  In playing with it enabled today I haven't had the error fire just yet, but I'm sure it will eventually.

**Comment by nomad980** [comment] 2016-09-06 18:39
I disabled it for now. I am currently not playing with the AH. I might just make it so that only my AH character uses it.

**Closed as completed** 2016-10-05 07:46 UTC
